### ISSUE TITLE
Customization...

### ISSUE THREAD

**Issue by askuhn** [mgedmin/indicator-netspeed#1]
I was wondering if there is any way to make this nice port function a bit more like the old applet used to:
1. Is there any way to convert the displayed values to bits instead of bytes?
2. Is it possible to display the up & down values without clicking? (perhaps even inverting it and placing the net total in the menu instead?)

Also, perhaps a "quit" choice in the menu?  The only way i can shut it off is by killing the process.

This is by no means a demand for you to act upon my questions, just (someone that has no idea how to code :P) hoping for a little help...Thanks very much!

**Comment by mgedmin** [comment]
I find the constant width changes that push other indicators around incredibly distracting, so much that I can't actually use it.  This means that, unfortunately, I'm not interested in working on it any more.

Sorry!

**Comment by askuhn** [comment]
Sad to hear it, but thanks for your reply  :)

**Comment by mgedmin** [comment]
FWIW I added a "quit" menu item.

**Comment by askuhn** [comment]
I did notice that, and thank you, but unless I can figure out a way to get some of my other requests, then it is not very useful for me, either.  Thanks again, though! :)
