### ISSUE TITLE
install fails on ubuntu 14.10 beta final

### ISSUE THREAD

**Issue by denispr** [mgedmin/indicator-netspeed#7]
Here is the output:

denis@denis-portable:~$ sudo apt-get install indicator-netspeed 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indicator-netspeed : Depends: libgtop2-7 (>= 2.22.3) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by mgedmin** [comment]
Utopic has libgtop2-10.

Where did you find a PPA with indicator-netspeed?

**Comment by denispr** [comment]
I followed the instructions here:
http://itsfoss.com/netspeed-applet-indicator-ubuntu-14-04/
that provide  http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/ ppa.
But these instructions were for 14.04, maybe I should have not followed them, and should have installed from github ?

**Comment by mgedmin** [comment]
Yeah, build from source, or ask the PPA owner to build packages for Utopic.

**Comment by mgedmin** [comment]
Yeah, build from source, or ask the PPA owner to build packages for Utopic.

**Comment by denispr** [comment]
Thank you for the tip, I'll try to build from source.
